#define DNA_BLOCK_SIZE_DNACOLOR 18

#define DNA_MUTANT_DNACOLOR_BLOCK 16
#define DNA_SKIN_COLOR_BLOCK 17
//#define DNA_EARS_BLOCK
#define DNA_EARS_DNACOLOR_BLOCK 18
#define DNA_ANTHRO_TAIL_BLOCK 19
//#define DNA_TAIL_BLOCK
#define DNA_TAIL_DNACOLOR_BLOCK 20
//#define DNA_SNOUT_BLOCK
#define DNA_SNOUT_DNACOLOR_BLOCK 21
//#define DNA_HORNS_BLOCK
#define DNA_HORNS_DNACOLOR_BLOCK 22
//#define DNA_FRILLS_BLOCK
#define DNA_FRILLS_DNACOLOR_BLOCK 23
//#define DNA_SPINES_BLOCK
#define DNA_SPINES_DNACOLOR_BLOCK 24
//#define DNA_MOTH_WINGS_BLOCK
#define DNA_MOTH_WINGS_DNACOLOR_BLOCK 25
//#define DNA_MOTH_ANTENNAE_BLOCK
#define DNA_MOTH_ANTENNAE_DNACOLOR_BLOCK 26

/// This number needs to equal the total number of DNA feature blocks
#define DNA_FEATURE_BLOCKS 26
